From ubuntu:xenial 

RUN apt-get -y update
RUN apt-get -y install libgtk2.0-0 libgconf2-4 \
    libnss3 libasound2 libxtst6 libcanberra-gtk-module \
    libgl1-mesa-glx zip gcc g++ make openssl libssl-dev \
    libbz2-dev libreadline-dev libsqlite3-dev sqlite \ 
    gnupg curl apt-transport-https libxss1




