version: '3'
services:
  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
#      - ./postgres/init:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: post001
      POSTGRES_USER: root1
      POSTGRES_PASSWORD: passwd12345
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres001
    restart: always
    user: root
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 8000:80
    volumes:
#      - ./pgadmin:/var/lib/pgadmin/storage
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.net
      PGADMIN_DEFAULT_PASSWORD: passwd
    hostname: pgadmin4
    restart: always
  
volumes:
  postgres:
  pgadmin:
